name: Setup and update common workflows

on:
  schedule:
  - cron: "0 2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Read config
        run: |
          echo "SETTINGS={}" >> $GITHUB_ENV
          if [[ -f "./.github/workflows-config.json" ]]; then
            echo "SETTINGS=$( jq .setupWorkflows './.github/workflows-config.json' )" >> $GITHUB_ENV
          fi

      - name: Checkout default branch
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_WORKFLOWS_TOKEN }}

      - name: Checkout common workflows repository
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          path: ckeditor4-workflows-common
          repository: ckeditor/ckeditor4-workflows-common
          ref: master

      - name: Setup workflows directory
        run: |
          mkdir -p .github/workflows

      - name: Synchronize workflow files
        run: |
          rsync -a --include='*/' --include='*.yml' --exclude='*' ./ckeditor4-workflows-common/workflows/ ./.github/workflows/
          if [[ $(git status ./.github/workflows/ --porcelain) ]]; then
              echo "HAS_CHANGES=1" >> $GITHUB_ENV
          fi

      - name: Cleanup common workflows artifacts
        run: |
          rm -rf ckeditor4-workflows-common

      - name: Prepare PR branch
        if: env.HAS_CHANGES == 1
        run: |
          echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV
          pushAsPullRequest=$(echo ${{ env.SETTINGS }} | jq ".pushAsPullRequest")
          if [[ "$pushAsPullRequest" == true ]]; then
            echo "AS_PR=1" >> $GITHUB_ENV
            echo "BRANCH_NAME=t/setup-workflows-update" >> $GITHUB_ENV
            git checkout -b t/setup-workflows-update
          fi

      - name: Add changes
        if: env.HAS_CHANGES == 1
        run: |
          git config --local user.email "${{ secrets.GH_BOT_EMAIL }}"
          git config --local user.name "${{ secrets.GH_BOT_USERNAME }}"
          git add .github/workflows
          git commit -m "Update common workflows."

      - name: Push changes
        if: env.HAS_CHANGES == 1
        # https://github.com/marketplace/actions/github-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_WORKFLOWS_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}

      - name: Create PR
        if: env.AS_PR == 1
        # https://github.com/marketplace/actions/github-pull-request-action
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ env.BRANCH_NAME }}"
          destination_branch: "${{ github.ref }}"
          pr_title: "Update 'setup-workflows' workflow"
          pr_body: "Update 'setup-workflows' workflow."
          github_token: ${{ secrets.GITHUB_TOKEN }}
